/**
 * Popular VS Code themes bundled as built-in Bender themes.
 * Each is converted from its canonical VS Code JSON color tokens via importVsCodeTheme().
 * Keeping raw VS Code payloads here makes it easy to update or add new themes.
 */
import { importVsCodeTheme } from "./convert.js";
import type { BenderTheme } from "./types.js";

function from(payload: Record<string, unknown>): BenderTheme {
  return importVsCodeTheme({ payload }).theme;
}

// ── Dark themes ───────────────────────────────────────────────────────────────

export const TOKYO_NIGHT: BenderTheme = from({
  name: "Tokyo Night",
  type: "dark",
  colors: {
    "editor.background": "#1a1b2e",
    "editor.foreground": "#c0caf5",
    "sideBar.background": "#16161e",
    "activityBar.background": "#1a1b2e",
    "panel.background": "#16161e",
    "panel.border": "#292e42",
    "sideBar.border": "#292e42",
    "editorGroupHeader.tabsBackground": "#0d0e1a",
    "editorWidget.background": "#1f2335",
    "dropdown.background": "#1f2335",
    "input.background": "#1d2033",
    "input.border": "#292e42",
    "button.background": "#7aa2f7",
    "button.foreground": "#1a1b2e",
    "focusBorder": "#7aa2f7",
    "textLink.foreground": "#7aa2f7",
    "terminal.background": "#1a1b2e",
    "terminal.ansiGreen": "#9ece6a",
    "terminal.ansiYellow": "#e0af68",
    "terminal.ansiRed": "#f7768e",
    "diffEditor.insertedLineBackground": "#9ece6a22",
    "diffEditor.removedLineBackground": "#f7768e22",
    "gitDecoration.addedResourceForeground": "#9ece6a",
    "gitDecoration.deletedResourceForeground": "#f7768e",
    "editorLineNumber.foreground": "#3b4261",
    "descriptionForeground": "#9aa5ce",
  },
});

export const ONE_DARK_PRO: BenderTheme = from({
  name: "One Dark Pro",
  type: "dark",
  colors: {
    "editor.background": "#282c34",
    "editor.foreground": "#abb2bf",
    "sideBar.background": "#21252b",
    "activityBar.background": "#21252b",
    "panel.background": "#21252b",
    "panel.border": "#3a3f4b",
    "sideBar.border": "#181a1f",
    "editorGroupHeader.tabsBackground": "#21252b",
    "editorWidget.background": "#21252b",
    "dropdown.background": "#21252b",
    "input.background": "#1d2026",
    "input.border": "#3a3f4b",
    "button.background": "#4d78cc",
    "button.foreground": "#ffffff",
    "focusBorder": "#528bff",
    "textLink.foreground": "#61afef",
    "terminal.background": "#282c34",
    "terminal.ansiGreen": "#98c379",
    "terminal.ansiYellow": "#e5c07b",
    "terminal.ansiRed": "#e06c75",
    "diffEditor.insertedLineBackground": "#98c37922",
    "diffEditor.removedLineBackground": "#e06c7522",
    "editorLineNumber.foreground": "#495162",
    "descriptionForeground": "#848b98",
  },
});

export const DRACULA: BenderTheme = from({
  name: "Dracula",
  type: "dark",
  colors: {
    "editor.background": "#282a36",
    "editor.foreground": "#f8f8f2",
    "sideBar.background": "#21222c",
    "activityBar.background": "#21222c",
    "panel.background": "#21222c",
    "panel.border": "#44475a",
    "sideBar.border": "#191a21",
    "editorGroupHeader.tabsBackground": "#21222c",
    "editorWidget.background": "#21222c",
    "dropdown.background": "#343746",
    "input.background": "#313341",
    "input.border": "#44475a",
    "button.background": "#bd93f9",
    "button.foreground": "#f8f8f2",
    "focusBorder": "#bd93f9",
    "textLink.foreground": "#8be9fd",
    "terminal.background": "#282a36",
    "terminal.ansiGreen": "#50fa7b",
    "terminal.ansiYellow": "#f1fa8c",
    "terminal.ansiRed": "#ff5555",
    "diffEditor.insertedLineBackground": "#50fa7b22",
    "diffEditor.removedLineBackground": "#ff555522",
    "editorLineNumber.foreground": "#6272a4",
    "descriptionForeground": "#6272a4",
  },
});

export const CATPPUCCIN_MOCHA: BenderTheme = from({
  name: "Catppuccin Mocha",
  type: "dark",
  colors: {
    "editor.background": "#1e1e2e",
    "editor.foreground": "#cdd6f4",
    "sideBar.background": "#181825",
    "activityBar.background": "#181825",
    "panel.background": "#181825",
    "panel.border": "#313244",
    "sideBar.border": "#11111b",
    "editorGroupHeader.tabsBackground": "#11111b",
    "editorWidget.background": "#1e1e2e",
    "dropdown.background": "#181825",
    "input.background": "#181825",
    "input.border": "#313244",
    "button.background": "#89b4fa",
    "button.foreground": "#1e1e2e",
    "focusBorder": "#89b4fa",
    "textLink.foreground": "#89b4fa",
    "terminal.background": "#1e1e2e",
    "terminal.ansiGreen": "#a6e3a1",
    "terminal.ansiYellow": "#f9e2af",
    "terminal.ansiRed": "#f38ba8",
    "diffEditor.insertedLineBackground": "#a6e3a122",
    "diffEditor.removedLineBackground": "#f38ba822",
    "editorLineNumber.foreground": "#45475a",
    "descriptionForeground": "#6c7086",
  },
});

export const GITHUB_DARK: BenderTheme = from({
  name: "GitHub Dark",
  type: "dark",
  colors: {
    "editor.background": "#0d1117",
    "editor.foreground": "#c9d1d9",
    "sideBar.background": "#161b22",
    "activityBar.background": "#161b22",
    "panel.background": "#161b22",
    "panel.border": "#30363d",
    "sideBar.border": "#21262d",
    "editorGroupHeader.tabsBackground": "#161b22",
    "editorWidget.background": "#161b22",
    "dropdown.background": "#161b22",
    "input.background": "#0d1117",
    "input.border": "#30363d",
    "button.background": "#238636",
    "button.foreground": "#ffffff",
    "focusBorder": "#58a6ff",
    "textLink.foreground": "#58a6ff",
    "terminal.background": "#0d1117",
    "terminal.ansiGreen": "#3fb950",
    "terminal.ansiYellow": "#d29922",
    "terminal.ansiRed": "#f85149",
    "diffEditor.insertedLineBackground": "#3fb95022",
    "diffEditor.removedLineBackground": "#f8514922",
    "editorLineNumber.foreground": "#3b434b",
    "descriptionForeground": "#8b949e",
  },
});

export const SOLARIZED_DARK: BenderTheme = from({
  name: "Solarized Dark",
  type: "dark",
  colors: {
    "editor.background": "#002b36",
    "editor.foreground": "#839496",
    "sideBar.background": "#073642",
    "activityBar.background": "#073642",
    "panel.background": "#073642",
    "panel.border": "#094e61",
    "sideBar.border": "#01343f",
    "editorGroupHeader.tabsBackground": "#073642",
    "editorWidget.background": "#073642",
    "dropdown.background": "#073642",
    "input.background": "#00212b",
    "input.border": "#094e61",
    "button.background": "#268bd2",
    "button.foreground": "#fdf6e3",
    "focusBorder": "#268bd2",
    "textLink.foreground": "#268bd2",
    "terminal.background": "#002b36",
    "terminal.ansiGreen": "#859900",
    "terminal.ansiYellow": "#b58900",
    "terminal.ansiRed": "#dc322f",
    "diffEditor.insertedLineBackground": "#85990022",
    "diffEditor.removedLineBackground": "#dc322f22",
    "editorLineNumber.foreground": "#4a6370",
    "descriptionForeground": "#657b83",
  },
});

// ── Light themes ──────────────────────────────────────────────────────────────

export const GITHUB_LIGHT: BenderTheme = from({
  name: "GitHub Light",
  type: "light",
  colors: {
    "editor.background": "#ffffff",
    "editor.foreground": "#24292f",
    "sideBar.background": "#f6f8fa",
    "activityBar.background": "#f6f8fa",
    "panel.background": "#f6f8fa",
    "panel.border": "#d0d7de",
    "sideBar.border": "#d0d7de",
    "editorGroupHeader.tabsBackground": "#f6f8fa",
    "editorWidget.background": "#f6f8fa",
    "dropdown.background": "#ffffff",
    "input.background": "#ffffff",
    "input.border": "#d0d7de",
    "button.background": "#2da44e",
    "button.foreground": "#ffffff",
    "focusBorder": "#0969da",
    "textLink.foreground": "#0969da",
    "terminal.background": "#ffffff",
    "terminal.ansiGreen": "#116329",
    "terminal.ansiYellow": "#9a6700",
    "terminal.ansiRed": "#cf222e",
    "diffEditor.insertedLineBackground": "#11632922",
    "diffEditor.removedLineBackground": "#cf222e22",
    "editorLineNumber.foreground": "#8c959f",
    "descriptionForeground": "#57606a",
  },
});

export const SOLARIZED_LIGHT: BenderTheme = from({
  name: "Solarized Light",
  type: "light",
  colors: {
    "editor.background": "#fdf6e3",
    "editor.foreground": "#657b83",
    "sideBar.background": "#eee8d5",
    "activityBar.background": "#eee8d5",
    "panel.background": "#eee8d5",
    "panel.border": "#cfc9b5",
    "sideBar.border": "#d6d0bc",
    "editorGroupHeader.tabsBackground": "#eee8d5",
    "editorWidget.background": "#eee8d5",
    "dropdown.background": "#fdf6e3",
    "input.background": "#fdf6e3",
    "input.border": "#cfc9b5",
    "button.background": "#268bd2",
    "button.foreground": "#fdf6e3",
    "focusBorder": "#268bd2",
    "textLink.foreground": "#268bd2",
    "terminal.background": "#fdf6e3",
    "terminal.ansiGreen": "#859900",
    "terminal.ansiYellow": "#b58900",
    "terminal.ansiRed": "#dc322f",
    "editorLineNumber.foreground": "#93a1a1",
    "descriptionForeground": "#839496",
  },
});

// ── Export all bundled themes (in display order) ──────────────────────────────

export const BUNDLED_THEMES: BenderTheme[] = [
  TOKYO_NIGHT,
  ONE_DARK_PRO,
  DRACULA,
  CATPPUCCIN_MOCHA,
  GITHUB_DARK,
  SOLARIZED_DARK,
  GITHUB_LIGHT,
  SOLARIZED_LIGHT,
];
