import type { BenderTheme } from "./types.js";
import { BUNDLED_THEMES } from "./bundled.js";

const DEFAULT_ZINC_DARK = {
  "50": "#fafafa",
  "100": "#f4f4f5",
  "200": "#e4e4e7",
  "300": "#d4d4d8",
  "400": "#a1a1aa",
  "500": "#71717a",
  "600": "#52525b",
  "700": "#3f3f46",
  "800": "#27272a",
  "900": "#18181b",
  "925": "#111113",
  "950": "#09090b",
} as const;

const DEFAULT_ZINC_LIGHT = {
  "50": "#09090b",
  "100": "#111113",
  "200": "#18181b",
  "300": "#27272a",
  "400": "#3f3f46",
  "500": "#71717a",
  "600": "#a1a1aa",
  "700": "#d4d4d8",
  "800": "#e4e4e7",
  "900": "#f4f4f5",
  "925": "#f8f8f9",
  "950": "#fafafa",
} as const;

export const DEFAULT_THEME_ID = "bender-default-dark";
export const LIGHT_THEME_ID = "bender-default-light";

export const BENDER_DEFAULT_DARK_THEME: BenderTheme = {
  schemaVersion: 1,
  id: DEFAULT_THEME_ID,
  name: "Bender Default (Dark)",
  appearance: "dark",
  description: "Built-in Bender dark theme.",
  author: "Bender",
  ui: {
    colors: {
      appBg: DEFAULT_ZINC_DARK["950"],
      panelBg: DEFAULT_ZINC_DARK["925"],
      panelAltBg: DEFAULT_ZINC_DARK["900"],
      elevatedBg: DEFAULT_ZINC_DARK["800"],
      overlayBg: "#09090be6",
      textPrimary: DEFAULT_ZINC_DARK["50"],
      textSecondary: DEFAULT_ZINC_DARK["300"],
      textMuted: DEFAULT_ZINC_DARK["500"],
      textInverse: DEFAULT_ZINC_DARK["950"],
      borderDefault: DEFAULT_ZINC_DARK["800"],
      borderMuted: DEFAULT_ZINC_DARK["900"],
      borderStrong: DEFAULT_ZINC_DARK["700"],
      accent: DEFAULT_ZINC_DARK["200"],
      accentFg: DEFAULT_ZINC_DARK["950"],
      focusRing: DEFAULT_ZINC_DARK["200"],
      success: "#34d399",
      warning: "#fbbf24",
      danger: "#f87171",
      diffAdded: "#34d399",
      diffRemoved: "#f87171",
      inputBg: DEFAULT_ZINC_DARK["925"],
      inputBorder: DEFAULT_ZINC_DARK["800"],
      inputBorderHover: DEFAULT_ZINC_DARK["700"],
      inputBorderFocus: DEFAULT_ZINC_DARK["100"],
      inputDisabledBg: "#0f0f10",
      inputDisabledBorder: "#1f1f22",
      inputDisabledText: DEFAULT_ZINC_DARK["500"],
      checkboxBg: DEFAULT_ZINC_DARK["925"],
      checkboxBorder: DEFAULT_ZINC_DARK["700"],
      checkboxCheckedBg: DEFAULT_ZINC_DARK["800"],
      checkboxCheckedBorder: DEFAULT_ZINC_DARK["300"],
      checkboxIndicator: DEFAULT_ZINC_DARK["300"],
      scrollbarThumb: DEFAULT_ZINC_DARK["700"],
      scrollbarThumbHover: DEFAULT_ZINC_DARK["600"],
      codeInlineBg: DEFAULT_ZINC_DARK["800"],
      codeInlineFg: DEFAULT_ZINC_DARK["200"],
      codeBlockBg: DEFAULT_ZINC_DARK["900"],
      codeBlockBorder: DEFAULT_ZINC_DARK["800"],
    },
    radius: {
      sm: "4px",
      md: "6px",
      lg: "8px",
      xl: "12px",
    },
    legacy: {
      zinc: { ...DEFAULT_ZINC_DARK },
    },
  },
};

export const BENDER_DEFAULT_LIGHT_THEME: BenderTheme = {
  schemaVersion: 1,
  id: LIGHT_THEME_ID,
  name: "Bender Default (Light)",
  appearance: "light",
  description: "Built-in Bender light theme.",
  author: "Bender",
  ui: {
    colors: {
      appBg: "#fafafa",
      panelBg: "#f4f4f5",
      panelAltBg: "#e4e4e7",
      elevatedBg: "#ffffff",
      overlayBg: "#fafafacc",
      textPrimary: "#09090b",
      textSecondary: "#27272a",
      textMuted: "#71717a",
      textInverse: "#fafafa",
      borderDefault: "#d4d4d8",
      borderMuted: "#e4e4e7",
      borderStrong: "#a1a1aa",
      accent: "#18181b",
      accentFg: "#fafafa",
      focusRing: "#18181b",
      success: "#059669",
      warning: "#d97706",
      danger: "#dc2626",
      diffAdded: "#059669",
      diffRemoved: "#dc2626",
      inputBg: "#ffffff",
      inputBorder: "#d4d4d8",
      inputBorderHover: "#a1a1aa",
      inputBorderFocus: "#18181b",
      inputDisabledBg: "#f4f4f5",
      inputDisabledBorder: "#e4e4e7",
      inputDisabledText: "#a1a1aa",
      checkboxBg: "#ffffff",
      checkboxBorder: "#a1a1aa",
      checkboxCheckedBg: "#f4f4f5",
      checkboxCheckedBorder: "#18181b",
      checkboxIndicator: "#18181b",
      scrollbarThumb: "#d4d4d8",
      scrollbarThumbHover: "#a1a1aa",
      codeInlineBg: "#f4f4f5",
      codeInlineFg: "#18181b",
      codeBlockBg: "#f4f4f5",
      codeBlockBorder: "#d4d4d8",
    },
    radius: {
      sm: "4px",
      md: "6px",
      lg: "8px",
      xl: "12px",
    },
    legacy: {
      zinc: { ...DEFAULT_ZINC_LIGHT },
    },
  },
};

// Bender defaults first (pinned), then popular VS Code themes alphabetically
export const BUILTIN_THEMES: BenderTheme[] = [
  BENDER_DEFAULT_DARK_THEME,
  BENDER_DEFAULT_LIGHT_THEME,
  ...BUNDLED_THEMES,
];
